Docker
ribaguifi/django-orchestra pull request #3
Opened 2021-01-29 13:29 UTC by cayop

There are some in the INSTALLDEV.md for the implementation for develop works with dockers.
I Changed the Dockerfile because we need fixed the version of the operating system. Actually it is debian 10.
And we need install python3.6 in that version.

I modify orchestra-admin and orchestra-deploy for automatized the process for install it.
I'm not try run the tests. And maybe when we see the problems with the test we need return to modify the implementation of this process.

2021-01-29 13:37 UTC, slamora requested changes
Can you check if `scripts/containers/orchestra-deploy` is a copy of https://raw.githubusercontent.com/ribaguifi/django-orchestra/master/scripts/containers/deploy.sh ??

2021-01-30 14:26 UTC, cayop commented
It's true, I moved it.
And I changed the rest of the commands of the orchestra of "orchestra/management/commands" dir

2021-01-30 14:27 UTC, cayop commented
It's true, I moved it.
And I changed the rest of the commands of the orchestra of "orchestra/management/commands" dir

2021-02-01 11:05 UTC, slamora requested changes

2021-02-01 11:05 UTC, slamora commented on scripts/containers/deploy.sh
> +	orch_version=$(python3 -c "from orchestra import get_version; print(get_version());" 2> /dev/null || echo '')
Please, check the indentation.

2021-02-01 11:05 UTC, slamora commented on scripts/containers/deploy.sh
> +	    run sudo apt-get update
Underindented lines?

2021-02-01 11:05 UTC, slamora commented on scripts/containers/deploy.sh
> +	run sudo pip3 install -e $home/django-orchestra
Underindented lines?

2021-02-01 11:05 UTC, slamora commented on scripts/containers/deploy.sh
> +	pg_version=$(psql --version | head -n1 | awk '{print $3}' | sed -e "s,\..*,,")
Underindented lines?

2021-02-01 11:45 UTC, merged